### PR TITLE
Windows: support BusTypeAta

### PR DESCRIPTION
**Pull request by a-ilin**
This patch adds support for some devices with bus identifier BusTypeAta.

I have such a laptop Lenovo X220 with Samsung SSD 850 Pro.

### CODE REVIEW

**Comment by a-ilin** [comment]
r0m30, you are correct. SSD 850 Pro is SATA drive, it's specs here: [link](http://www.samsung.com/us/computer/memory-storage/MZ-7KE512BW)

The drive configured to be AHCI. I'm using Windows 7 x64 with all updates and drivers installed.
The laptop uses Intel Core i7 Sandy Bridge 2620M, the chipset is Intel QM67 rev. 4

**Comment by r0m30** [comment]
Thanks, I'll pull and merge this for the next release.

**Comment by cristim** [comment]
I forked the project into a new Github organization, and it's available at https://github.com/sedutil/sedutil

Please join us there and re-submit this PR, we promise to merge it timely after passing the code review.

**Comment by r0m30** [comment]
Implemented in V1.15

**Pull request closed without merging**
