### PR TITLE
Enterprise drive and output format improvements

### PR DESCRIPTION
**Pull request by kendmerry**
Add some changes, primarily to the Enterprise drive code, to do a few things:
 o Make it easier to operate on drives that haven't had a password set yet.
 o Make the initial setup code work without erring out on Seagate and HGST drives.
 o Add an output mode without the time/date to be a little more readable.
 o Make sedutil exit statuses consistent. In particular, it's important to know when we get SP_BUSY status back, so we can take action (reset the drive) to restore communication with the encryption processor.

I have tested this on FreeBSD, using the changes from @amotin with Seagate and HGST SED drives.

Sponsored by: Spectra Logic

### CODE REVIEW

**Comment by cristim** [comment]
I forked the project into a new Github organization, and it's available at https://github.com/sedutil/sedutil

Please also send this PR there, we promise to merge it timely after passing the code review.

**Comment by kendmerry** [comment]
Sounds good, thank you!  I just submitted the PR there.

Ken
— 
Ken Merry
ken@kdm.org

**Comment by r0m30** [comment]
Sorry for the delay, I'm template challenged.

I was with you right up to the log I messages to stdout, this conflicts with the PBA.  I know you are enterprise focused and don't have a shadow MBR, and PSID Revert either isn't implemented or is unique to the vendor so you wouldn't have ever noticed this. 

We will also need a signed contributor agreement to merge this code.

**Comment by r0m30** [comment]
I took a look a the conflicts and they are very minor.  We both updated the copyrite statement and scanDisk was moved to DtaDevOS.

**Comment by kendmerry** [comment]
I can fix the stdout / stderr issue.  Perhaps hiding it behind a command line option would do the trick.

As for the contributor agreement, I'll have to get management and legal approval for that.  We'll see what they say.

**Comment by r0m30** [comment]
That would be great, you can make split output the default if you'd like, the PBA is the only place I think it will make any difference.

Yes, the contributor agreement means a lot more work for you, sorry.

**Comment by kendmerry** [comment]
I switched things around so that the default is to print to stdout and stderr for sedutil, and the PBA has log style output to stderr only as it was before.

I also merged with the latest changes, the conflicts are minor.

Management and legal approved the contributor agreement, I'll email that to you separately.

**Comment by kendmerry** [comment]
Hmm, I don't see an email address on your profile.  Send me email (ken@kdm.org) and I'll send you the signed contributor agreement. Thanks!

**Comment by r0m30** [comment]
You did a new push just as I was building a new release.  Can we close this and start a new one?

**Comment by kendmerry** [comment]
Sure. I'll take out the latest change.

**Comment by kendmerry** [comment]
Oh, I see you've already pulled in the changes so yes, I'll close this one and open a new one.

**Pull request closed without merging**
